Balanceo de /invertir y /gamble para encajar con una economia balanceada
adrgarcha/mariwano pull request #52
Opened 2024-07-20 19:59 UTC by davider0

2024-07-28 16:45 UTC, davider0 commented on src/commands/economy/gamble.ts
> +    const amountWon = Math.round(amount * (Math.random() + 0.95));
Antes habia un 3 multiplicando y ahora no, ahora se gana como máximo menos del doble de lo apostado

2024-07-28 16:45 UTC, davider0 commented on src/commands/economy/leaderboard.ts
> +      const balance: BigInt = BigInt(user?.balance!);
Se pasa de Number a BigInt para que detecte el balance como válido y se pueda hacer /leaderboard

2024-07-28 16:45 UTC, davider0 commented on src/commands/economy/gamble.ts
> +    const hasWin = Math.random() > Math.random();
La cantidad que se gana depende completamente de Math.random()

2024-07-28 16:45 UTC, davider0 commented on src/commands/fun/invertir.ts
> +          }`
En los textos ahora se pueden ver las variables del modelo User que tienen que ver con invertir para saber exactamente como de rentable es un canal, el dinero apostado, etc., esto es una característica debug que podría ser quitada

2024-07-28 16:45 UTC, davider0 commented on src/commands/fun/invertir.ts
> +          );
Las diferencias del de antes a ahora son:

- Antes se multiplicaba por el factorial de investFactor, ahora la operación no es de multiplicación sino de suma
- El investFactor se multiplicaba también por la proporción de dinero en la cuenta del usuario en función de lo invertido, ahora se multiplica la raiz cuadrada de investFactor, haciendo casi insignificante la proporción

En resumen prácticamente el beneficio que se gana es que le devuelva el dinero invertido más una cantidad muy pequeña dependiendo de la rentabilidad del canal

2024-07-28 16:45 UTC, davider0 commented on src/commands/fun/invertir.ts
> +          targetUser.balance += ganancias;
Ahora, el usuario a quien se invirtió también recibe ganancias, esto antes funcionaba deficientemente

2024-07-28 16:45 UTC, davider0 commented on src/commands/fun/invertir.ts
> +                factorial(Math.abs(user.investFactor))
La fórmula de cuando se pierden ganancias es la misma

2024-07-28 16:45 UTC, davider0 commented on src/commands/fun/invertir.ts
> +          targetUser.balance -= ganancias;
El usuario al que se invirtió el dinero también perdería dinero en este caso

2024-07-28 16:45 UTC, davider0 commented on src/utils/readFiles.ts
> +         const filePath = path.join(childPath, file).replace('C:','file:///C:');
Este es el fix del error ESM que hace que funcione en Windows

2024-08-06 10:24 UTC, adrgarcha requested changes
Por lo general los cambios están bien, pero son necesarios los siguientes cambios para que los comandos se encuentren lo mas balanceados posibles:

- El comando /invertir sigue estando desbalanceado, al menos para los usuarios ya existentes, ya que tienen guardados en BD unos datos bastante inflados respecto a su economía. Solo en el caso de que esto este presente unicamente en el servidor de testing se podrían reducir los números en BD para ver si los cambios están correctamente.
- El usuario en el que se invierte se lleva con el 100% del dinero ganado, lo cual no creo que sea lo mas correcto. Lo suyo seria que se llevase un porcentaje bajo que se encuentre por debajo del 10%.
- No se presentan decimales en la BD, aunque en los comandos si aparecen decimales de forma que habría que imponer una restricción para no poner cantidades decimales en los comandos de economía. Revisar si Discord te permite aplicar esa restricción directamente en la definición del comando. En el caso de que esto no fuera posible, habría que imponer una restricción manualmente en cada comando de economía en el que el bot envié un mensaje indicando que no se pueden poner números decimales.

Por lo demás, no he visto ningún tipo de error. He arreglado el comando /leaderboard y he realizado un formateo de los comandos para que se mantenga el mismo en todos los archivos. Dentro de poco introduciré un cambio para que se mantenga el mismo formato en todo el proyecto con Prettier.

2024-08-07 16:02 UTC, adrgarcha requested changes
Todo los cambios anteriores funcionan correctamente. Sin embargo, el comando /invertir sigue un poco desbalanceado, pero puede que sea porque los números se han inflado de tanto usarlos en las pruebas con cantidades enormes de dinero.

Como de momento parece que esta balanceado, lo único que solicito es que se diferencien los subcomandos mediante un switch/case y que cada uno tenga las validaciones y resultados que corresponda. De forma que se tenga control sobre cada uno de los subcomandos, fuera de los switch/case solo deben existir validaciones y variables comunes para los tres subcomandos.

2024-08-07 18:57 UTC, adrgarcha approved these changes

2024-08-07 18:58 UTC, merged